#!/usr/bin/env python3
"""Generate repetitive C++ source files for parser performance guard tests.

Usage:
    perf_gen.py --test <name> --output <path> --repeat-count <n>

Available tests:
    qualified_known_type_arg
    qualified_template_call_template_arg
    typedef_owned_functional_cast
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def gen_qualified_known_type_arg(repeat: int) -> str:
    """
    Stress-tests parsing of qualified alias-template type arguments.

    Generates a pack instantiation with `repeat` occurrences of `ns::id_t<int>`.
    Exercises the fast-path for qualified known-type template arguments.
    """
    args = ",\n".join(f"  ns::id_t<int>" for _ in range(repeat))
    return (
        "// Generated by perf_gen.py -- do not edit\n"
        "namespace ns {\n"
        "template <class T> struct id { using type = T; };\n"
        "template <class T> using id_t = typename id<T>::type;\n"
        "template <class... Ts> struct pack {};\n"
        "} // namespace ns\n"
        f"using big_pack = ns::pack<\n{args}\n>;\n"
        "int main() { return 0; }\n"
    )


def gen_qualified_template_call_template_arg(repeat: int) -> str:
    """
    Stress-tests parsing of call-like template arguments that are themselves
    template specialisations.

    Each repeated method has a default template argument of the form
    `enable_if<chooser_t<U1, U2>::template check<U1, U2>(), bool>::type`.
    """
    methods: list[str] = []
    for i in range(repeat):
        methods.append(
            f"  template <class U1_{i}, class U2_{i},"
            f" class = typename enable_if<"
            f"chooser_t<U1_{i}, U2_{i}>::template check<U1_{i}, U2_{i}>()"
            f", bool>::type>\n"
            f"  static void f{i}();"
        )

    return (
        "// Generated by perf_gen.py -- do not edit\n"
        "template <bool B, class T = void>\n"
        "struct enable_if { using type = T; };\n"
        "template <class A, class B>\n"
        "struct is_same { static constexpr bool value = false; };\n"
        "template <class T1, class T2>\n"
        "struct pair_like {\n"
        "  template <bool, class U1, class U2>\n"
        "  struct chooser {\n"
        "    template <class X1, class X2>\n"
        "    static constexpr bool check() { return true; }\n"
        "  };\n"
        "  template <class U1, class U2>\n"
        "  using chooser_t = chooser<\n"
        "    !is_same<T1, U1>::value || !is_same<T2, U2>::value, U1, U2>;\n"
        + "\n".join(methods) + "\n"
        "};\n"
        "int main() { return 0; }\n"
    )


def gen_typedef_owned_functional_cast(repeat: int) -> str:
    """
    Stress-tests parsing of functional-cast expressions using a typedef member
    as the type name (e.g. `value_type()`  and `static_cast<value_type>(0)`).
    """
    methods: list[str] = []
    for i in range(repeat):
        methods.append(
            f"  static constexpr value_type f{i}() {{ return value_type(); }}\n"
            f"  static constexpr value_type g{i}() {{ return static_cast<value_type>(0); }}"
        )

    return (
        "// Generated by perf_gen.py -- do not edit\n"
        "template <class T> struct box {\n"
        "  typedef T value_type;\n"
        + "\n".join(methods) + "\n"
        "};\n"
        "int main() { return 0; }\n"
    )


# ---------------------------------------------------------------------------

GENERATORS = {
    "qualified_known_type_arg": gen_qualified_known_type_arg,
    "qualified_template_call_template_arg": gen_qualified_template_call_template_arg,
    "typedef_owned_functional_cast": gen_typedef_owned_functional_cast,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--test", required=True, choices=GENERATORS,
                        help="Which perf test to generate")
    parser.add_argument("--output", required=True,
                        help="Path for the generated .cpp file")
    parser.add_argument("--repeat-count", type=int, required=True,
                        help="Number of repeated constructs to emit")
    args = parser.parse_args()

    source = GENERATORS[args.test](args.repeat_count)
    Path(args.output).write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
