typedef int (*twenty_arg_fn)(int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int,
                             int);

int call_local(twenty_arg_fn f,
               int u,
               int v,
               int w,
               int x,
               int y,
               int z,
               int q,
               int r,
               int s,
               int t,
               int m,
               int n,
               int o,
               int p,
               int h,
               int j,
               int k,
               int l,
               int a) {
  twenty_arg_fn g = f;
  return g(u, v, w, x, y, z, q, r, s, t, m, n, o, p, h, j, k, l, a, 20);
}
