typedef int (*twenty_six_arg_fn)(int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int,
                                 int);

int call_local(twenty_six_arg_fn f,
               int u,
               int v,
               int w,
               int x,
               int y,
               int z,
               int q,
               int r,
               int s,
               int t,
               int m,
               int n,
               int o,
               int p,
               int h,
               int j,
               int k,
               int l,
               int a,
               int b,
               int c,
               int d,
               int e,
               int g,
               int i) {
  twenty_six_arg_fn ifn = f;
  return ifn(u, v, w, x, y, z, q, r, s, t, m, n, o, p, h, j, k, l, a, b, c, d, e, g, i, 26);
}
