#!/usr/bin/env python3
"""Generate idea 44 parser-disambiguation manifests and parse-only tests."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import product
from pathlib import Path
from typing import Iterable, TypeVar


@dataclass(frozen=True)
class OwnerSpelling:
    label: str
    text: str


@dataclass(frozen=True)
class DeclaratorShape:
    label: str
    abstract_template: str
    named_template: str

    def render_abstract(self, owner: str) -> str:
        return self.abstract_template.format(owner=owner)

    def render_named(self, owner: str, name: str) -> str:
        return self.named_template.format(owner=owner, name=name)


@dataclass(frozen=True)
class ParseContext:
    label: str
    example_template: str
    test_template: str
    scope: str = "function"

    def render_example(self, type_id: str, named_decl: str) -> str:
        return self.example_template.format(type_id=type_id, named_decl=named_decl)

    def render_test_snippet(self, type_id: str, named_decl: str) -> str:
        return self.test_template.format(type_id=type_id, named_decl=named_decl)


OWNERS: tuple[OwnerSpelling, ...] = (
    OwnerSpelling("simple", "T"),
    OwnerSpelling("qualified", "ns::T"),
    OwnerSpelling("global_qualified", "::ns::T"),
    OwnerSpelling("dependent_typename", "typename H<T>::Type"),
    OwnerSpelling(
        "dependent_template_member",
        "typename H<T>::template Rebind<U>::Type",
    ),
)

DECLARATORS: tuple[DeclaratorShape, ...] = (
    DeclaratorShape("pointer", "{owner}*", "{owner}* {name}"),
    DeclaratorShape("lvalue_ref", "{owner}&", "{owner}& {name}"),
    DeclaratorShape("rvalue_ref", "{owner}&&", "{owner}&& {name}"),
    DeclaratorShape("cv_pointer", "{owner}* const", "{owner}* const {name}"),
    DeclaratorShape("grouped_pointer", "{owner} (*)", "{owner} (*{name})"),
    DeclaratorShape("grouped_lvalue_ref", "{owner} (&)", "{owner} (&{name})"),
    DeclaratorShape("grouped_rvalue_ref", "{owner} (&&)", "{owner} (&&{name})"),
    DeclaratorShape("member_pointer", "{owner} C::*", "{owner} C::*{name}"),
    DeclaratorShape("function_pointer", "{owner} (*)(Arg)", "{owner} (*{name})(Arg)"),
    DeclaratorShape(
        "function_lvalue_ref",
        "{owner} (&)(Arg)",
        "{owner} (&{name})(Arg)",
    ),
    DeclaratorShape(
        "function_rvalue_ref",
        "{owner} (&&)(Arg)",
        "{owner} (&&{name})(Arg)",
    ),
    DeclaratorShape(
        "member_function_pointer",
        "{owner} (C::*)(Arg)",
        "{owner} (C::*{name})(Arg)",
    ),
)

CONTEXTS: tuple[ParseContext, ...] = (
    ParseContext("c_style_cast_target", "({type_id})expr", "    ({type_id})expr;\n"),
    ParseContext("local_declaration", "{named_decl};", "    {named_decl};\n"),
    ParseContext(
        "parameter_declaration",
        "void probe({named_decl});",
        "void probe({named_decl});\n",
        scope="global",
    ),
    ParseContext(
        "parenthesized_type_id_consumer",
        "sizeof({type_id})",
        "    int width = sizeof({type_id});\n    (void)width;\n",
    ),
    ParseContext(
        "ambiguous_statement_context",
        "{named_decl}(value);",
        "    {named_decl}(value);\n",
    ),
)

SUPPORT_PREAMBLE = """// Generated by scripts/generate_parser_disambiguation_matrix.py.
// Keep this file in sync with the source manifest for idea 44.
// RUN: %c4cll --parse-only %s

struct T {
    int value;
};

struct Arg {
    int value;
};

struct C {
    int field;
    int method(Arg);
};

struct U {
    int value;
};

namespace ns {
struct T {
    int value;
};
}

template <class X>
struct H {
    using Type = X;

    template <class Y>
    struct Rebind {
        using Type = Y;
    };
};

void* expr = 0;
int value = 0;
"""

TItem = TypeVar("TItem")


def select_items(items: tuple[TItem, ...], selected_labels: set[str]) -> tuple[TItem, ...]:
    if not selected_labels:
        return items
    return tuple(item for item in items if getattr(item, "label") in selected_labels)


def iter_combinations(
    owners: tuple[OwnerSpelling, ...],
    declarators: tuple[DeclaratorShape, ...],
    contexts: tuple[ParseContext, ...],
) -> Iterable[tuple[int, OwnerSpelling, DeclaratorShape, ParseContext]]:
    owner_labels = {owner.label for owner in owners}
    declarator_labels = {declarator.label for declarator in declarators}
    context_labels = {context.label for context in contexts}

    index = 1
    for owner, declarator, context in product(OWNERS, DECLARATORS, CONTEXTS):
        if (
            owner.label in owner_labels
            and declarator.label in declarator_labels
            and context.label in context_labels
        ):
            yield index, owner, declarator, context
        index += 1


def build_entries(
    owners: tuple[OwnerSpelling, ...],
    declarators: tuple[DeclaratorShape, ...],
    contexts: tuple[ParseContext, ...],
    verification: str,
) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for index, owner, declarator, context in iter_combinations(
        owners, declarators, contexts
    ):
        type_id = declarator.render_abstract(owner.text)
        named_decl = declarator.render_named(owner.text, "value")
        entries.append(
            {
                "index": f"{index:03d}",
                "owner_label": owner.label,
                "owner_text": owner.text,
                "declarator_label": declarator.label,
                "type_id": type_id,
                "named_decl": named_decl,
                "context_label": context.label,
                "verification": verification,
                "expected_stage": "parse",
                "source_template": context.label,
                "high_risk": "yes" if "grouped" in declarator.label else "no",
                "example": context.render_example(type_id, named_decl),
            }
        )
    return entries


def format_entry(entry: dict[str, str]) -> str:
    return (
        f'{entry["index"]}. '
        f'owner={entry["owner_label"]} '
        f'owner_text="{entry["owner_text"]}" '
        f'declarator={entry["declarator_label"]} '
        f'type_id="{entry["type_id"]}" '
        f'named_decl="{entry["named_decl"]}" '
        f"context={entry['context_label']} "
        f"verification={entry['verification']} "
        f"expected_stage={entry['expected_stage']} "
        f"source_template={entry['source_template']} "
        f"high_risk={entry['high_risk']} "
        f'example="{entry["example"]}"'
    )


def render_flat(entries: list[dict[str, str]]) -> str:
    return "\n".join(format_entry(entry) for entry in entries) + "\n"


def render_grouped(entries: list[dict[str, str]], group_by: str) -> str:
    assert group_by in {"owner", "declarator"}

    label_key = "owner_label" if group_by == "owner" else "declarator_label"
    value_key = "owner_text" if group_by == "owner" else "type_id"
    ordered_labels = (
        [owner.label for owner in OWNERS]
        if group_by == "owner"
        else [declarator.label for declarator in DECLARATORS]
    )

    chunks: list[str] = []
    for label in ordered_labels:
        group_entries = [entry for entry in entries if entry[label_key] == label]
        if not group_entries:
            continue
        chunks.append(f"## {label}")
        sample_values: list[str] = []
        for entry in group_entries:
            sample = entry[value_key]
            if sample not in sample_values:
                sample_values.append(sample)
        chunks.append("samples: " + ", ".join(sample_values[:5]))
        for entry in group_entries:
            chunks.append(format_entry(entry))
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def render_test_file(
    entry: dict[str, str],
    context_lookup: dict[str, ParseContext],
) -> str:
    context = context_lookup[entry["context_label"]]
    metadata = (
        f"// owner: {entry['owner_label']}\n"
        f"// declarator: {entry['declarator_label']}\n"
        f"// context: {entry['context_label']}\n"
        f"// verification: {entry['verification']}\n\n"
    )
    body = context.render_test_snippet(entry["type_id"], entry["named_decl"])

    if context.scope == "global":
        return (
            f"{SUPPORT_PREAMBLE}\n"
            f"{metadata}"
            f"{body}\n"
            "int main() {\n"
            "    return 0;\n"
            "}\n"
        )

    return (
        f"{SUPPORT_PREAMBLE}\n"
        f"{metadata}"
        "int main() {\n"
        f"{body}"
        "    return 0;\n"
        "}\n"
    )


def emit_test_files(entries: list[dict[str, str]], test_root: Path) -> None:
    context_lookup = {context.label: context for context in CONTEXTS}
    test_root.mkdir(parents=True, exist_ok=True)
    for existing in test_root.glob("*.cpp"):
        existing.unlink()
    for entry in entries:
        filename = (
            f"owner_{entry['owner_label']}"
            f"__decl_{entry['declarator_label']}"
            f"__ctx_{entry['context_label']}"
            f"__{entry['verification']}.cpp"
        )
        (test_root / filename).write_text(
            render_test_file(entry, context_lookup),
            encoding="ascii",
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        help="Write the generated matrix to this file instead of stdout.",
    )
    parser.add_argument(
        "--group-by",
        choices=("owner", "declarator"),
        help="Group output by a top-level matrix dimension.",
    )
    parser.add_argument(
        "--emit-grouped-files",
        action="store_true",
        help="Write flat, owner-grouped, and declarator-grouped files next to --output.",
    )
    parser.add_argument(
        "--verification",
        default="parse_only",
        help="Verification tier recorded in emitted manifest entries and tests.",
    )
    parser.add_argument(
        "--owners",
        nargs="*",
        default=(),
        help="Restrict generation to the listed owner labels.",
    )
    parser.add_argument(
        "--declarators",
        nargs="*",
        default=(),
        help="Restrict generation to the listed declarator labels.",
    )
    parser.add_argument(
        "--contexts",
        nargs="*",
        default=(),
        help="Restrict generation to the listed context labels.",
    )
    parser.add_argument(
        "--test-root",
        help="Write generated .cpp test files into this directory.",
    )
    args = parser.parse_args()

    owners = select_items(OWNERS, set(args.owners))
    declarators = select_items(DECLARATORS, set(args.declarators))
    contexts = select_items(CONTEXTS, set(args.contexts))
    entries = build_entries(owners, declarators, contexts, args.verification)
    payload = render_grouped(entries, args.group_by) if args.group_by else render_flat(entries)

    if args.output:
        with open(args.output, "w", encoding="ascii") as f:
            f.write(payload)
        if args.emit_grouped_files:
            output_path = Path(args.output)
            stem = output_path.stem
            suffix = output_path.suffix
            owner_path = output_path.with_name(f"{stem}_by_owner{suffix}")
            declarator_path = output_path.with_name(f"{stem}_by_declarator{suffix}")
            owner_path.write_text(render_grouped(entries, "owner"), encoding="ascii")
            declarator_path.write_text(
                render_grouped(entries, "declarator"),
                encoding="ascii",
            )
    else:
        print(payload, end="")

    if args.test_root:
        emit_test_files(entries, Path(args.test_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
